spring:
  kafka:
    listener:
      missing-topics-fatal: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.jdbc.time_zone]": UTC
  datasource:
    url: jdbc:h2:mem:kotlin-kafka-broker;MODE=PostgreSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
logging:
  level:
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type.descriptor.sql]": trace
    "[org.hibernate.transaction.JDBCTransaction]": debug
    "[org.hibernate.jdbc.ConnectionManager]": debug
    "[org.springframework.orm.JpaTransactionManager]": debug
    "[org.springframework.jdbc]": debug
